# Generated from contracts/openapi.json.
from typing import Any
from pathlib import Path
from pydantic import BaseModel
from ._types import (Body_restore_backup as Body_restore_backup, Body_upload_source as Body_upload_source, ContactPolicy as ContactPolicy, CreateRecord as CreateRecord, FamilyChange as FamilyChange, FamilyCreate as FamilyCreate, FeedbackRequest as FeedbackRequest, HTTPValidationError as HTTPValidationError, HostEvent as HostEvent, MaintenanceRequest as MaintenanceRequest, ModelRole as ModelRole, RecallItem as RecallItem, RecallRequest as RecallRequest, RecallResult as RecallResult, RecordInput as RecordInput, RecordResult as RecordResult, RelationRequest as RelationRequest, RevisionInput as RevisionInput, ScheduleChange as ScheduleChange, ScheduleInput as ScheduleInput, Scope as Scope, ScopeResult as ScopeResult, SessionBoundary as SessionBoundary, SourceInput as SourceInput, SourceResult as SourceResult, ValidationError as ValidationError, WebSource as WebSource)
class Client:
    def __init__(self, url: str = ..., token: str | None = ..., *, root: str | Path | None = ..., transport: Any = ..., timeout: float = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: Any) -> None: ...
    def call(self, operation: str, body: Any = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> Any: ...
    def upload(self, path: str | Path, metadata: BaseModel | dict) -> SourceResult: ...
    def health(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def receive_source(self, body: SourceInput | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> SourceResult: ...
    def receive_batch(self, body: list[SourceInput] | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def upload_source(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> SourceResult: ...
    def read_source(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> SourceResult: ...
    def import_url(self, body: WebSource | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def read_attachment(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> Any: ...
    def read_clip(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> Any: ...
    def read_page(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> Any: ...
    def create_memory(self, body: CreateRecord | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> RecordResult: ...
    def list_memories(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def recall(self, body: RecallRequest | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> RecallResult: ...
    def read_memory(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> RecordResult: ...
    def read_revisions(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def revise_memory(self, body: RevisionInput | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> RecordResult: ...
    def delete_object(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def preview_deletion(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def create_relation(self, body: RelationRequest | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def record_feedback(self, body: FeedbackRequest | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def session_boundary(self, body: SessionBoundary | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def host_event(self, body: HostEvent | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def run_maintenance(self, body: MaintenanceRequest | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def create_download(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def download_export(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> Any: ...
    def restore_backup(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def list_scopes(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def list_jobs(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def control_job(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def list_families(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def create_family(self, body: FamilyCreate | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def read_family(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def change_family(self, body: FamilyChange | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def read_graph(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def configure_contact(self, body: ContactPolicy | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def list_contact(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def create_schedule(self, body: ScheduleInput | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def change_schedule(self, body: ScheduleChange | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def acknowledge_delivery(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def contact_tick(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def overview(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def read_settings(self, body: Any | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def configure_settings(self, body: dict[str, Any] | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
    def configure_models(self, body: dict[str, ModelRole] | BaseModel | None = ..., *, params: dict | None = ..., files: Any = ..., **path_params: Any) -> dict[str, Any]: ...
class DeliveryInbox:
    def __init__(self, path: str | Path) -> None: ...
    def accept(self, delivery: dict, handler: Any) -> bool: ...
