// Generated by scripts/generate_contract.py; do not edit.
export const operations = {
  "health": {
    "method": "GET",
    "path": "/v1/health",
    "parameters": [],
    "body": {}
  },
  "receive_source": {
    "method": "POST",
    "path": "/v1/sources",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/SourceInput"
          }
        }
      },
      "required": true
    }
  },
  "receive_batch": {
    "method": "POST",
    "path": "/v1/sources/batch",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "items": {
              "$ref": "#/components/schemas/SourceInput"
            },
            "type": "array",
            "maxItems": 100,
            "title": "Sources"
          }
        }
      },
      "required": true
    }
  },
  "upload_source": {
    "method": "POST",
    "path": "/v1/sources/upload",
    "parameters": [],
    "body": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "$ref": "#/components/schemas/Body_upload_source"
          }
        }
      },
      "required": true
    }
  },
  "read_source": {
    "method": "GET",
    "path": "/v1/sources/{source_id}",
    "parameters": [
      {
        "name": "source_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Source Id"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "",
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 200,
          "minimum": 1,
          "default": 100,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "import_url": {
    "method": "POST",
    "path": "/v1/sources/url",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/WebSource"
          }
        }
      },
      "required": true
    }
  },
  "read_attachment": {
    "method": "GET",
    "path": "/v1/sources/{source_id}/content",
    "parameters": [
      {
        "name": "source_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Source Id"
        }
      }
    ],
    "body": {}
  },
  "read_clip": {
    "method": "GET",
    "path": "/v1/sources/{source_id}/clip",
    "parameters": [
      {
        "name": "source_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Source Id"
        }
      },
      {
        "name": "start",
        "in": "query",
        "required": false,
        "schema": {
          "type": "number",
          "default": 0,
          "title": "Start"
        }
      },
      {
        "name": "end",
        "in": "query",
        "required": false,
        "schema": {
          "type": "number",
          "default": 30,
          "title": "End"
        }
      }
    ],
    "body": {}
  },
  "read_page": {
    "method": "GET",
    "path": "/v1/sources/{source_id}/page",
    "parameters": [
      {
        "name": "source_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Source Id"
        }
      },
      {
        "name": "page",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "minimum": 1,
          "default": 1,
          "title": "Page"
        }
      }
    ],
    "body": {}
  },
  "create_memory": {
    "method": "POST",
    "path": "/v1/memories",
    "parameters": [],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CreateRecord"
          }
        }
      }
    }
  },
  "list_memories": {
    "method": "GET",
    "path": "/v1/memories",
    "parameters": [
      {
        "name": "project",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "personal",
          "title": "Project"
        }
      },
      {
        "name": "persona",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Persona"
        }
      },
      {
        "name": "collection",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Collection"
        }
      },
      {
        "name": "world",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "real",
          "title": "World"
        }
      },
      {
        "name": "kind",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Kind"
        }
      },
      {
        "name": "status",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Status"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 200,
          "minimum": 1,
          "default": 50,
          "title": "Limit"
        }
      },
      {
        "name": "group",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "enum": [
                "diary",
                "timeline"
              ],
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Group"
        }
      },
      {
        "name": "query",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "maxLength": 4000
            },
            {
              "type": "null"
            }
          ],
          "title": "Query"
        }
      }
    ],
    "body": {}
  },
  "recall": {
    "method": "POST",
    "path": "/v1/recall",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/RecallRequest"
          }
        }
      },
      "required": true
    }
  },
  "read_memory": {
    "method": "GET",
    "path": "/v1/memories/{record_id}",
    "parameters": [
      {
        "name": "record_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Record Id"
        }
      },
      {
        "name": "at",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "At"
        }
      },
      {
        "name": "known_at",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Known At"
        }
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "title": "Offset"
        }
      },
      {
        "name": "length",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 32000,
          "minimum": 1,
          "default": 12000,
          "title": "Length"
        }
      },
      {
        "name": "budget",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 32000,
          "minimum": 1,
          "default": 4000,
          "title": "Budget"
        }
      },
      {
        "name": "session",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Session"
        }
      }
    ],
    "body": {}
  },
  "read_revisions": {
    "method": "GET",
    "path": "/v1/memories/{record_id}/revisions",
    "parameters": [
      {
        "name": "record_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Record Id"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "default": 2147483647,
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "minimum": 1,
          "default": 20,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "revise_memory": {
    "method": "POST",
    "path": "/v1/memories/{record_id}/revisions",
    "parameters": [
      {
        "name": "record_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Record Id"
        }
      }
    ],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/RevisionInput"
          }
        }
      }
    }
  },
  "delete_object": {
    "method": "DELETE",
    "path": "/v1/objects/{object_id}",
    "parameters": [
      {
        "name": "object_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Object Id"
        }
      }
    ],
    "body": {}
  },
  "preview_deletion": {
    "method": "GET",
    "path": "/v1/objects/{object_id}/deletion",
    "parameters": [
      {
        "name": "object_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Object Id"
        }
      }
    ],
    "body": {}
  },
  "create_relation": {
    "method": "POST",
    "path": "/v1/relations",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/RelationRequest"
          }
        }
      },
      "required": true
    }
  },
  "record_feedback": {
    "method": "POST",
    "path": "/v1/feedback",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/FeedbackRequest"
          }
        }
      },
      "required": true
    }
  },
  "session_boundary": {
    "method": "POST",
    "path": "/v1/sessions/boundary",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/SessionBoundary"
          }
        }
      },
      "required": true
    }
  },
  "host_event": {
    "method": "POST",
    "path": "/v1/host/events",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/HostEvent"
          }
        }
      },
      "required": true
    }
  },
  "run_maintenance": {
    "method": "POST",
    "path": "/v1/maintenance",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/MaintenanceRequest"
          }
        }
      },
      "required": true
    }
  },
  "create_download": {
    "method": "POST",
    "path": "/v1/maintenance/downloads/{kind}",
    "parameters": [
      {
        "name": "kind",
        "in": "path",
        "required": true,
        "schema": {
          "enum": [
            "backup",
            "export"
          ],
          "type": "string",
          "title": "Kind"
        }
      }
    ],
    "body": {}
  },
  "download_export": {
    "method": "GET",
    "path": "/v1/maintenance/files/{name}",
    "parameters": [
      {
        "name": "name",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Name"
        }
      }
    ],
    "body": {}
  },
  "restore_backup": {
    "method": "POST",
    "path": "/v1/maintenance/restore",
    "parameters": [],
    "body": {
      "content": {
        "multipart/form-data": {
          "schema": {
            "$ref": "#/components/schemas/Body_restore_backup"
          }
        }
      },
      "required": true
    }
  },
  "list_scopes": {
    "method": "GET",
    "path": "/v1/scopes",
    "parameters": [],
    "body": {}
  },
  "list_jobs": {
    "method": "GET",
    "path": "/v1/jobs",
    "parameters": [
      {
        "name": "state",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "State"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "",
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 200,
          "minimum": 1,
          "default": 50,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "control_job": {
    "method": "POST",
    "path": "/v1/jobs/{job_id}/{action}",
    "parameters": [
      {
        "name": "job_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Job Id"
        }
      },
      {
        "name": "action",
        "in": "path",
        "required": true,
        "schema": {
          "enum": [
            "cancel",
            "retry"
          ],
          "type": "string",
          "title": "Action"
        }
      }
    ],
    "body": {}
  },
  "list_families": {
    "method": "GET",
    "path": "/v1/families",
    "parameters": [
      {
        "name": "project",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "personal",
          "title": "Project"
        }
      },
      {
        "name": "persona",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Persona"
        }
      },
      {
        "name": "collection",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Collection"
        }
      },
      {
        "name": "world",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "real",
          "title": "World"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "",
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "minimum": 1,
          "default": 50,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "create_family": {
    "method": "POST",
    "path": "/v1/families",
    "parameters": [],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/FamilyCreate"
          }
        }
      }
    }
  },
  "read_family": {
    "method": "GET",
    "path": "/v1/families/{family_id}",
    "parameters": [
      {
        "name": "family_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Family Id"
        }
      },
      {
        "name": "offset",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "title": "Offset"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 200,
          "minimum": 1,
          "default": 100,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "change_family": {
    "method": "POST",
    "path": "/v1/families/{family_id}",
    "parameters": [
      {
        "name": "family_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Family Id"
        }
      }
    ],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/FamilyChange"
          }
        }
      }
    }
  },
  "read_graph": {
    "method": "GET",
    "path": "/v1/graph",
    "parameters": [
      {
        "name": "project",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "personal",
          "title": "Project"
        }
      },
      {
        "name": "persona",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Persona"
        }
      },
      {
        "name": "collection",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "default",
          "title": "Collection"
        }
      },
      {
        "name": "world",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "real",
          "title": "World"
        }
      },
      {
        "name": "family_id",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Family Id"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 300,
          "minimum": 1,
          "default": 150,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "configure_contact": {
    "method": "PUT",
    "path": "/v1/contact/policies",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ContactPolicy"
          }
        }
      },
      "required": true
    }
  },
  "list_contact": {
    "method": "GET",
    "path": "/v1/contact/{table}",
    "parameters": [
      {
        "name": "table",
        "in": "path",
        "required": true,
        "schema": {
          "enum": [
            "policies",
            "schedules",
            "outbox"
          ],
          "type": "string",
          "title": "Table"
        }
      },
      {
        "name": "cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "",
          "title": "Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 200,
          "minimum": 1,
          "default": 50,
          "title": "Limit"
        }
      }
    ],
    "body": {}
  },
  "create_schedule": {
    "method": "POST",
    "path": "/v1/contact/schedules",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ScheduleInput"
          }
        }
      },
      "required": true
    }
  },
  "change_schedule": {
    "method": "POST",
    "path": "/v1/contact/schedules/{schedule_id}",
    "parameters": [
      {
        "name": "schedule_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Schedule Id"
        }
      }
    ],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ScheduleChange"
          }
        }
      }
    }
  },
  "acknowledge_delivery": {
    "method": "POST",
    "path": "/v1/contact/outbox/{delivery_id}/ack",
    "parameters": [
      {
        "name": "delivery_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Delivery Id"
        }
      }
    ],
    "body": {}
  },
  "contact_tick": {
    "method": "POST",
    "path": "/v1/contact/tick",
    "parameters": [
      {
        "name": "deliver",
        "in": "query",
        "required": false,
        "schema": {
          "type": "boolean",
          "default": false,
          "title": "Deliver"
        }
      }
    ],
    "body": {}
  },
  "overview": {
    "method": "GET",
    "path": "/v1/overview",
    "parameters": [],
    "body": {}
  },
  "read_settings": {
    "method": "GET",
    "path": "/v1/settings/{key}",
    "parameters": [
      {
        "name": "key",
        "in": "path",
        "required": true,
        "schema": {
          "enum": [
            "models",
            "budgets",
            "scenarios",
            "connections",
            "maintenance",
            "parsers"
          ],
          "type": "string",
          "title": "Key"
        }
      }
    ],
    "body": {}
  },
  "configure_settings": {
    "method": "PUT",
    "path": "/v1/settings/{key}",
    "parameters": [
      {
        "name": "key",
        "in": "path",
        "required": true,
        "schema": {
          "enum": [
            "budgets",
            "scenarios",
            "connections",
            "maintenance",
            "parsers"
          ],
          "type": "string",
          "title": "Key"
        }
      }
    ],
    "body": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "type": "object",
            "additionalProperties": true,
            "title": "Value"
          }
        }
      }
    }
  },
  "configure_models": {
    "method": "PUT",
    "path": "/v1/settings/models",
    "parameters": [],
    "body": {
      "content": {
        "application/json": {
          "schema": {
            "additionalProperties": {
              "$ref": "#/components/schemas/ModelRole"
            },
            "type": "object",
            "title": "Request"
          }
        }
      },
      "required": true
    }
  }
} as const;
export type Operation = keyof typeof operations;
