/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Source */
        post: operations["receive_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Batch */
        post: operations["receive_batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Source */
        post: operations["upload_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Source */
        get: operations["read_source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Url */
        post: operations["import_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Attachment */
        get: operations["read_attachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/clip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Clip */
        get: operations["read_clip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{source_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Page */
        get: operations["read_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories"];
        put?: never;
        /** Create Memory */
        post: operations["create_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recall */
        post: operations["recall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Memory */
        get: operations["read_memory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{record_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Revisions */
        get: operations["read_revisions"];
        put?: never;
        /** Revise Memory */
        post: operations["revise_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Object */
        delete: operations["delete_object"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/objects/{object_id}/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Deletion */
        get: operations["preview_deletion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Relation */
        post: operations["create_relation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Feedback */
        post: operations["record_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/boundary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Boundary */
        post: operations["session_boundary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/host/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host Event */
        post: operations["host_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Maintenance */
        post: operations["run_maintenance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/downloads/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Download */
        post: operations["create_download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/maintenance/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scopes */
        get: operations["list_scopes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Control Job */
        post: operations["control_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Families */
        get: operations["list_families"];
        put?: never;
        /** Create Family */
        post: operations["create_family"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Family */
        get: operations["read_family"];
        put?: never;
        /** Change Family */
        post: operations["change_family"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Graph */
        get: operations["read_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure Contact */
        put: operations["configure_contact"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/{table}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contact */
        get: operations["list_contact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Schedule */
        post: operations["create_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Schedule */
        post: operations["change_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/outbox/{delivery_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Delivery */
        post: operations["acknowledge_delivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contact/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contact Tick */
        post: operations["contact_tick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings"];
        /** Configure Settings */
        put: operations["configure_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configure Models */
        put: operations["configure_models"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_restore_backup */
        Body_restore_backup: {
            /** File */
            file: string;
        };
        /** Body_upload_source */
        Body_upload_source: {
            /** Metadata */
            metadata: string;
            /** File */
            file: string;
        };
        /** ContactPolicy */
        ContactPolicy: {
            /**
             * Id
             * @default default
             */
            id?: string;
            scope?: components["schemas"]["Scope"];
            /**
             * Enabled
             * @default false
             */
            enabled?: boolean;
            /** Channel */
            channel?: string | null;
            /**
             * Timezone
             * @default UTC
             */
            timezone?: string;
            /**
             * Quiet Start
             * @default 22
             */
            quiet_start?: number;
            /**
             * Quiet End
             * @default 8
             */
            quiet_end?: number;
            /**
             * Max Per Day
             * @default 3
             */
            max_per_day?: number;
            /**
             * Min Interval Minutes
             * @default 60
             */
            min_interval_minutes?: number;
            /**
             * Require Confirmation
             * @default true
             */
            require_confirmation?: boolean;
            /**
             * Idempotent Channel
             * @default false
             */
            idempotent_channel?: boolean;
            /**
             * Greeting Text
             * @default 想聊聊今天的近况吗？
             */
            greeting_text?: string;
            /** Triggers */
            triggers?: ("reminder" | "commitment" | "anniversary" | "checkin" | "greeting")[];
            /** Allowed Kinds */
            allowed_kinds?: ("episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation")[];
        };
        /** CreateRecord */
        CreateRecord: {
            record: components["schemas"]["RecordInput"];
            /** Command Id */
            command_id: string;
        };
        /** FamilyChange */
        FamilyChange: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Action
             * @enum {string}
             */
            action: "publish" | "archive" | "merge" | "split" | "revise" | "rollback";
            /** Members */
            members?: string[] | null;
            /** Target */
            target?: string | null;
            /** Title */
            title?: string | null;
            /** Target Revision */
            target_revision?: number | null;
        };
        /** FamilyCreate */
        FamilyCreate: {
            scope?: components["schemas"]["Scope"];
            /** Title */
            title: string;
            /** Members */
            members: string[];
            /**
             * Kind
             * @default volume
             * @enum {string}
             */
            kind?: "family" | "volume";
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Record Id */
            record_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "displayed" | "read" | "adopted" | "verified" | "corrected" | "unknown" | "same_file_observed";
            /**
             * Session
             * @default
             */
            session?: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Key */
            key?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostEvent */
        HostEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "start" | "pre_action" | "tool" | "message" | "compact" | "end" | "boundary";
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** MaintenanceRequest */
        MaintenanceRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "organize" | "diary" | "summary" | "portrait" | "self_narrative" | "prediction" | "rebuild" | "build_vectors" | "purge_vectors";
            scope?: components["schemas"]["Scope"];
            /**
             * Since
             * @default
             */
            since?: string;
            /** Command Id */
            command_id: string;
            /**
             * Title
             * @default
             */
            title?: string;
        };
        /** ModelRole */
        ModelRole: {
            /** Endpoint */
            endpoint: string;
            /** Model */
            model: string;
            /**
             * Protocol
             * @default openai
             * @enum {string}
             */
            protocol?: "openai" | "anthropic";
            /** Api Key Env */
            api_key_env?: string | null;
            /**
             * Timeout Seconds
             * @default 60
             */
            timeout_seconds?: number;
            /** Dimensions */
            dimensions?: number | null;
            /**
             * Preprocessing
             * @default text-v1
             */
            preprocessing?: string;
            /**
             * Local Embedding
             * @default false
             */
            local_embedding?: boolean;
            /**
             * Input Price Per Million
             * @default 0
             */
            input_price_per_million?: number;
            /**
             * Output Price Per Million
             * @default 0
             */
            output_price_per_million?: number;
        };
        /** RecallItem */
        RecallItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "unverified" | "superseded" | "refuted" | "retracted" | "archived";
            /** Revision */
            revision: number;
            /** Source Ids */
            source_ids: string[];
            /** Read Url */
            read_url: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
            /** Generated */
            generated: boolean;
            /** Confirmation */
            confirmation: string;
        } & {
            [key: string]: unknown;
        };
        /** RecallRequest */
        RecallRequest: {
            /**
             * Query
             * @default
             */
            query?: string;
            scope?: components["schemas"]["Scope"];
            /**
             * Scenario
             * @default tool
             * @enum {string}
             */
            scenario?: "tool" | "companion" | "knowledge" | "research" | "creative" | "support" | "operations";
            /**
             * Mode
             * @default fast
             * @enum {string}
             */
            mode?: "fast" | "deep";
            /** At */
            at?: string | null;
            /** Known At */
            known_at?: string | null;
            /**
             * History
             * @default false
             */
            history?: boolean;
            /**
             * Include Shared
             * @default true
             */
            include_shared?: boolean;
            /** Kinds */
            kinds?: ("episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation")[];
            /**
             * Limit
             * @default 20
             */
            limit?: number;
            /** Budget */
            budget?: number | null;
            /** Session */
            session?: string | null;
            /**
             * Phase
             * @default search
             * @enum {string}
             */
            phase?: "search" | "startup" | "passive" | "read" | "compact";
            /**
             * Host Mode
             * @default append
             * @enum {string}
             */
            host_mode?: "append" | "replace";
            /** Vector */
            vector?: number[] | null;
            /** Index */
            index?: string | null;
            /**
             * Explain
             * @default false
             */
            explain?: boolean;
        };
        /** RecallResult */
        RecallResult: {
            /** Items */
            items: components["schemas"]["RecallItem"][];
            /** Text */
            text: string;
            /** Tokens */
            tokens: number;
            /** Budget */
            budget: number;
            /** Accounts */
            accounts: {
                [key: string]: number;
            };
            /** Generation */
            generation: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cursor */
            cursor: string | null;
            /** Session Used */
            session_used: number;
            /** Instruction Authority */
            instruction_authority: string;
        } & {
            [key: string]: unknown;
        };
        /** RecordInput */
        RecordInput: {
            /** Id */
            id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation";
            /**
             * Title
             * @default
             */
            title?: string;
            /** Content */
            content: string;
            scope?: components["schemas"]["Scope"];
            /** Source Ids */
            source_ids?: string[];
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Parent Id */
            parent_id?: string | null;
            /** Valid From */
            valid_from?: string;
            /** Valid Until */
            valid_until?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status?: "active" | "unverified" | "superseded" | "refuted" | "retracted" | "archived";
            /**
             * Confirmation
             * @default explicit
             * @enum {string}
             */
            confirmation?: "explicit" | "observed" | "documented" | "inferred" | "verified";
            /**
             * Importance
             * @default 0.5
             */
            importance?: number;
            /**
             * Generated
             * @default false
             */
            generated?: boolean;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Locator */
            locator?: {
                [key: string]: unknown;
            };
        };
        /** RecordResult */
        RecordResult: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation";
            /** Title */
            title: string;
            /** Content */
            content: string;
            scope: components["schemas"]["ScopeResult"];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "unverified" | "superseded" | "refuted" | "retracted" | "archived";
            /** Revision */
            revision: number;
            /** Source Ids */
            source_ids: string[];
            /** Generated */
            generated: boolean;
            /** Confirmation */
            confirmation: string;
            /** Valid From */
            valid_from: string;
            /** Valid Until */
            valid_until: string | null;
            /** Received At */
            received_at: string;
            /** Read Url */
            read_url: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** RelationRequest */
        RelationRequest: {
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Object */
            object: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /** RevisionInput */
        RevisionInput: {
            /** Expected Revision */
            expected_revision: number;
            /** Command Id */
            command_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "correct" | "confirm" | "retract" | "replace" | "refute" | "archive" | "restore" | "rollback";
            /** Content */
            content?: string | null;
            /**
             * Reason
             * @default
             */
            reason?: string;
            /** Replacement Id */
            replacement_id?: string | null;
            /** Target Revision */
            target_revision?: number | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
        };
        /** ScheduleChange */
        ScheduleChange: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Action
             * @enum {string}
             */
            action: "cancel" | "pause" | "resume" | "snooze" | "confirm";
            /** Due At */
            due_at?: string | null;
        };
        /** ScheduleInput */
        ScheduleInput: {
            /** Command Id */
            command_id: string;
            /**
             * Policy Id
             * @default default
             */
            policy_id?: string;
            /** Record Id */
            record_id: string;
            /** Due At */
            due_at: string;
            /**
             * Trigger
             * @default reminder
             * @enum {string}
             */
            trigger?: "reminder" | "commitment" | "anniversary" | "checkin" | "greeting";
            /**
             * Recurrence
             * @default none
             * @enum {string}
             */
            recurrence?: "none" | "daily" | "weekly" | "yearly";
        };
        /** Scope */
        Scope: {
            /**
             * Project
             * @default personal
             */
            project?: string;
            /**
             * Persona
             * @default default
             */
            persona?: string;
            /**
             * Collection
             * @default default
             */
            collection?: string;
            /**
             * World
             * @default real
             */
            world?: string;
        };
        /** ScopeResult */
        ScopeResult: {
            /** Project */
            project: string;
            /** Persona */
            persona: string;
            /** Collection */
            collection: string;
            /** World */
            world: string;
        };
        /** SessionBoundary */
        SessionBoundary: {
            /** Session */
            session: string;
            scope?: components["schemas"]["Scope"];
            /**
             * Event
             * @enum {string}
             */
            event: "start" | "end" | "compact" | "checkpoint";
            /**
             * Scenario
             * @default tool
             * @enum {string}
             */
            scenario?: "tool" | "companion" | "knowledge";
            /**
             * Host Mode
             * @default append
             * @enum {string}
             */
            host_mode?: "append" | "replace";
            /** Command Id */
            command_id: string;
            /** Checkpoint */
            checkpoint?: {
                [key: string]: unknown;
            };
        };
        /** SourceInput */
        SourceInput: {
            /** Namespace */
            namespace: string;
            /** Key */
            key: string;
            /**
             * Version
             * @default 1
             */
            version?: string;
            /**
             * Session
             * @default
             */
            session?: string;
            scope?: components["schemas"]["Scope"];
            /** Occurred At */
            occurred_at?: string;
            /**
             * Text
             * @default
             */
            text?: string;
            /**
             * Media Type
             * @default text/plain
             */
            media_type?: string;
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Origin
             * @default
             */
            origin?: string;
            /**
             * Kind
             * @default observation
             * @enum {string}
             */
            kind?: "episode" | "fact" | "state" | "preference" | "procedure" | "relationship" | "commitment" | "reminder" | "prediction" | "diary" | "summary" | "portrait" | "self_narrative" | "knowledge" | "checkpoint" | "observation";
            /**
             * Authority
             * @default explicit
             * @enum {string}
             */
            authority?: "explicit" | "operation" | "document" | "model";
            /**
             * Extract
             * @default false
             */
            extract?: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** SourceResult */
        SourceResult: {
            /** Id */
            id: string;
            /** Namespace */
            namespace: string;
            /** Key */
            key: string;
            /** Version */
            version: string;
            scope: components["schemas"]["ScopeResult"];
            /** Status */
            status: string;
            /** Revision */
            revision: number;
            /** Source Ids */
            source_ids: string[];
            /** Mechanical */
            mechanical: string;
            /** Model */
            model: string;
            /** Received At */
            received_at: string;
            /** Occurred At */
            occurred_at: string;
            /** Read Url */
            read_url: string;
            /** Title */
            title: string;
            /** Media Type */
            media_type: string;
            /** Byte Length */
            byte_length: number;
            /** Attachment Url */
            attachment_url: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebSource */
        WebSource: {
            /** Url */
            url: string;
            scope?: components["schemas"]["Scope"];
            /**
             * Title
             * @default
             */
            title?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    receive_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_batch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_attachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_clip: {
        parameters: {
            query?: {
                start?: number;
                end?: number;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_page: {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories: {
        parameters: {
            query?: {
                project?: string;
                persona?: string;
                collection?: string;
                world?: string;
                kind?: string | null;
                status?: string | null;
                cursor?: string | null;
                limit?: number;
                group?: ("diary" | "timeline") | null;
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecord"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecallResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_memory: {
        parameters: {
            query?: {
                at?: string | null;
                known_at?: string | null;
                offset?: number;
                length?: number;
                budget?: number;
                session?: string | null;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_revisions: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_object: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_deletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_boundary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionBoundary"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    host_event: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_maintenance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "backup" | "export";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_backup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_restore_backup"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                state?: string | null;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    control_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                action: "cancel" | "retry";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_families: {
        parameters: {
            query?: {
                project?: string;
                persona?: string;
                collection?: string;
                world?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_family: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_family: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                family_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_graph: {
        parameters: {
            query?: {
                project?: string;
                persona?: string;
                collection?: string;
                world?: string;
                family_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_contact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactPolicy"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contact: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                table: "policies" | "schedules" | "outbox";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_delivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contact_tick: {
        parameters: {
            query?: {
                deliver?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    read_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: "models" | "budgets" | "scenarios" | "connections" | "maintenance" | "parsers";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: "budgets" | "scenarios" | "connections" | "maintenance" | "parsers";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["ModelRole"];
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
