"""Generate both SDK operation tables and schemas from the running FastAPI contract."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from eventmem.core.api import create_app

ROOT = Path(__file__).resolve().parents[1]


def main():
    with tempfile.TemporaryDirectory() as temp:
        schema = create_app(
            temp, token="contract-generation-only", workers=False, mcp_enabled=False
        ).openapi()
    destination = ROOT / "contracts"
    destination.mkdir(exist_ok=True)
    (destination / "openapi.json").write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
    )
    operations = {}
    for path, methods in schema["paths"].items():
        for method, operation in methods.items():
            if "operationId" in operation:
                operations[operation["operationId"]] = {
                    "method": method.upper(),
                    "path": path,
                    "parameters": operation.get("parameters", []),
                    "body": operation.get("requestBody", {}),
                }
    py = (
        "# Generated by scripts/generate_contract.py; do not edit.\nOPERATIONS = "
        + repr(operations)
        + "\n"
    )
    sdk = ROOT / "src/eventmem/sdk"
    sdk.mkdir(exist_ok=True)
    (sdk / "_operations.py").write_text(py)
    ts = ROOT / "sdk/typescript/src"
    ts.mkdir(parents=True, exist_ok=True)
    (ts / "operations.ts").write_text(
        "// Generated by scripts/generate_contract.py; do not edit.\nexport const operations = "
        + json.dumps(operations, ensure_ascii=False, indent=2)
        + " as const;\nexport type Operation = keyof typeof operations;\n"
    )
    from python_types import generate

    generate(schema, sdk)
    print(f"Generated {len(operations)} operations")


if __name__ == "__main__":
    main()
